### ISSUE TITLE
Update appliance to 10.15.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud-docker/appliance#236]
The current 10.14.0 appliance CI gets Trivy problems reported because there are dependencies that now have CVEs against them.

Example CI is in renovate PR #235 

The current CI builds 10.14.0 and 10.13.4 which both have Trivy problems reported. IMO we should now just build 10.15.0.

**Comment by phil-davis** [comment]
@jnweiger do you do this sort of thing?

**Comment by jnweiger** [comment]
It is currently uncertain, if we want to have the actual appliance maintained.
But updating its docker image cannot hurt.

**Comment by phil-davis** [comment]
Done in #237
